name: Dependency Review

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '34 10 * * 3'

jobs:
  dependency-review:
    name: Review
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Scan with Dependency Review
        uses: actions/dependency-review-action@v4
